language: node_js
node_js:
  - '4'
sudo: false
script:
    - "npm run test"
after_script: "npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"