language: node_js
node_js:
  - '4'
sudo: false
script:
  - "npm run test-cov"
after_script: "cd test-cov && npm install coveralls && cat coverage.lcov | ./node_modules/coveralls/bin/coveralls.js && cd .. && rm -rf ./test-cov"