language: node_js
node_js:
  - '4'
sudo: false
script:
  - "npm run test-cov"
after_script: "npm install coveralls && cat test-cov/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./test-cov"